# Generated by Django 6.0.7 on 2026-07-17 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 닉네임입니다.'}, help_text='로그인 아이디. 농인은 이모지 조합, 청인은 글자를 씁니다.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='닉네임에 공백이나 특수 제어문자는 쓸 수 없습니다.', regex='^[^\\s\\x00-\\x1f\\x7f]+$')], verbose_name='닉네임'),
        ),
    ]
