# Generated by Django 6.0.7 on 2026-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='채팅에 이모지 아이디와 함께 표시할 한글 이름(선택).', max_length=20, verbose_name='표시 이름'),
        ),
    ]
