# Generated by Django 6.0.7 on 2026-07-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('emoji', models.CharField(default='🖐️', max_length=8)),
                ('video', models.FileField(blank=True, null=True, upload_to='sign_videos/')),
                ('external_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuickKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sign_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_keywords', to='sign_videos.signvideo')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
