# Generated by Django 6.0.7 on 2026-07-17 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_video', models.FileField(upload_to='sign_inputs/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', '분석을 준비하고 있어요'), ('PROCESSING', '수어를 분석하고 있어요'), ('COMPLETED', '분석이 완료되었어요'), ('FAILED', '수어를 인식하지 못했어요')], db_index=True, default='PENDING', max_length=20)),
                ('capture_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('onem2m_video_registered', models.BooleanField(default=False)),
                ('onem2m_result_registered', models.BooleanField(default=False)),
                ('onem2m_last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_translations', to='conversations.conversation')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SentenceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=200)),
                ('score', models.FloatField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_candidates', to='recognitions.signtranslation')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='RecognizedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('position', models.PositiveIntegerField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognized_keywords', to='recognitions.signtranslation')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='signtranslation',
            constraint=models.UniqueConstraint(condition=models.Q(('capture_id', ''), _negated=True), fields=('capture_id',), name='unique_capture_id'),
        ),
        migrations.AddConstraint(
            model_name='recognizedkeyword',
            constraint=models.UniqueConstraint(fields=('translation', 'position'), name='unique_keyword_position'),
        ),
    ]
