# Generated by Django 6.0.7 on 2026-07-17 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
        ('recognitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signtranslation',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_translations', to='conversations.conversation'),
        ),
    ]
