# Generated by Django 6.0.7 on 2026-07-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('recognitions', '0001_initial'),
        ('sign_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sign_translation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='recognitions.signtranslation'),
        ),
        migrations.AddField(
            model_name='signvideosequenceitem',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_video_sequence', to='conversations.message'),
        ),
        migrations.AddField(
            model_name='signvideosequenceitem',
            name='sign_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_items', to='sign_videos.signvideo'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_participant'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'id'], name='msg_conv_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='signvideosequenceitem',
            constraint=models.UniqueConstraint(fields=('message', 'position'), name='unique_sequence_position'),
        ),
    ]
